spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.16:3306/organic
    username: organic
    password: organic

mybatis:
  mapper-locations: mapper/**/*.xml
server:
  port: 7777
